### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by glentner**
This is a minimal first pass on adding "logging" as additional concept researchers should include in their python projects. Let's iterate on this before merging it in. I would like some feedback on what should be included.

### CODE REVIEW

**Comment by shwina** [comment]
@glentner 

Thanks very much for the contribution!

What do you think about making logging a part of a broader section on improving *usability*? Some other topics I can think of including would be for example writing command-line interfaces using [argparse](https://docs.python.org/3/library/argparse.html), and using configuration files.

**Comment by shwina** [comment]
The only change required would be to rename the section something like

> Making your code more usable

rather than 

>  Improved messaging using logging

**Comment by glentner** [comment]
A section on `argparse` would actually even benefit from building off what you already have in the way of best practices for package structure, in demonstrating how you add executable scripts to the package.

I can add those in and I'll update the PR.

**Comment by shwina** [comment]
This looks great to me. Thanks for the contribution! I will merge, but in the future may make the following changes:

* Use a concrete example rather than an abstract `do_science` program
* Use [semantic linefeeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) to be consistent with the rest of the source

Thanks again!

**Comment by glentner** [comment]
It looks like the heading levels are mismatched. On the index page it is showing the sub sections for logging but only the top level for argparse.

**Pull request merged**
